# Plugin Configuation
# -------------------
# Populate the following with your settings.
#
# 
# 
# Set the name that will be used to
# 1. access the plugin on the window object when the package is included
#    with <script> tags i.e. window.EXPORTED_PACKAGE_NAME
# 2. set the filename in the dist/ directory i.e. EXPORTED_PACKAGE_NAME[.min].js
export_name: EXPORTED_PACKAGE_NAME


script:
  src: 
    - index.js
    # Add scripts in order of inclusion e.g. 
    #  - src/A.js
    #  - src/B.js
  dest: dist/

# Any CSS included?
css:
  # 1. Pick an engine. Choose from: concat, less, stylus, sass
  engine: less
  # 2. Change any options.
  options: {}
  src: styles/*
  dest: 'dist/'


# These are the settings for the gulp-connect server.
webserver:
  open: spec/runner.html
  port: 4040
  livereload:
    port: 4041
  root:
    - 'spec/'
    - 'dist/'
    - '.'
    - 'bower_components/'


# Gulp-uglify settings
uglify: {}


#         -----------------------  STOP  -----------------------
# You should not need to modify the below. File an issue if you think you
# may need to. The config below may be modified upstream without notice.
foundation:
  repo: https://github.com/brianmhunt/knockout-plugin-foundation.git
  version: 0.0.1

header: |
  /*! <%=pkg.name%> v<%=pkg.version%> (<%=now.toLocaleString()%>)
      By: <%=pkg.author%> © <%=now.getFullYear()%>, license: <%=pkg.license%>.
      <%=pkg.repository.url%>
  */
  (function (root, factory) {
    if (typeof define === 'function' && define.amd) {
      define(['knockout'], factory);
    } else if (typeof exports === 'object') {
      module.exports = factory(require('knockout'));
    } else {
      root.<%=config.export_name%> = factory(root.ko);
    }
  }(this, function (ko) {
    var pluginExports = {};

footer: |
  return pluginExports;
  }));

watch:
  index.js
  spec/*
  config.yaml
